#ifndef C_CORD_EVENTS_H
#define C_CORD_EVENTS_H

enum EVENT_TYPE {
    CHANNEL_CREATE,
    CHANNEL_DELETE,
    CHANNEL_PINS_UPDATE,
    CHANNEL_UPDATE,
    GUILD_BAN_ADD,
    GUILD_BAN_REMOVE,
    GUILD_CREATE,
    GUILD_DELETE,
    GUILD_EMOJIS_UPDATE,
    GUILD_INTEGRATIONS_UPDATE,
    GUILD_MEMBER_ADD,
    GUILD_MEMBER_REMOVE,
    GUILD_MEMBER_UPDATE,
    GUILD_MEMBERS_CHUNK,
    GUILD_ROLE_CREATE,
    GUILD_ROLE_DELETE,
    GUILD_ROLE_UPDATE,
    GUILD_UPDATE,
    INVALID_SESSION,
    MESSAGE_BULK_DELETE,
    MESSAGE_CREATE,
    MESSAGE_DELETE,
    MESSAGE_REACTION_ADD,
    MESSAGE_REACTION_REMOVE,
    MESSAGE_REACTION_REMOVE_ALL,
    MESSAGE_UPDATE,
    PRESENCE_UPDATE,
    READY,
    RECONNECT,
    RESUMED,
    TYPING_START,
    USER_UPDATE,
    VOICE_SERVER_UPDATE,
    VOICE_STATE_UPDATE,
    WEBHOOKS_UPDATE
};

#endif //DISCORD_C_EVENTS_H
